/* Master data for the MVP. Kept as plain data so it can be reviewed by the
 * business side without reading any code. */

export const REGIONS = [
  { code: "osaka_city", prefecture: "大阪府", name: "大阪市" },
  { code: "osaka_north", prefecture: "大阪府", name: "大阪府北部" },
  { code: "hyogo_south", prefecture: "兵庫県", name: "兵庫県南東部" },
  { code: "kyoto_city", prefecture: "京都府", name: "京都市" },
  { code: "nara", prefecture: "奈良県", name: "奈良県" },
] as const;

export const OCCUPATIONS = [
  {
    code: "auto_mechanic",
    name: "自動車整備士",
    category: "整備・メンテナンス",
    description: "自動車の点検・整備・故障診断を担当",
    requiresTravel: false,
    requiresNightShift: false,
    requiresRelocation: false,
    minEducationLevel: null,
    managementRelevant: false,
    baseSalary: 4_000_000,
  },
  {
    code: "facility_maintenance",
    name: "設備保全",
    category: "整備・メンテナンス",
    description: "工場設備の予防保全・故障対応",
    requiresTravel: false,
    requiresNightShift: true,
    requiresRelocation: false,
    minEducationLevel: null,
    managementRelevant: false,
    baseSalary: 4_700_000,
  },
  {
    code: "field_service",
    name: "フィールドサービスエンジニア",
    category: "サービスエンジニア",
    description: "顧客先での機器の設置・保守・故障対応",
    requiresTravel: true,
    requiresNightShift: false,
    requiresRelocation: false,
    minEducationLevel: null,
    managementRelevant: false,
    baseSalary: 5_400_000,
  },
  {
    code: "industrial_service",
    name: "産業機械サービスエンジニア",
    category: "サービスエンジニア",
    description: "産業機械の据付・保守・技術サポート",
    requiresTravel: true,
    requiresNightShift: false,
    requiresRelocation: true,
    minEducationLevel: null,
    managementRelevant: false,
    baseSalary: 5_800_000,
  },
  {
    code: "electrician",
    name: "電気工事",
    category: "建設・設備",
    description: "電気設備の施工・保守",
    requiresTravel: false,
    requiresNightShift: true,
    requiresRelocation: false,
    minEducationLevel: null,
    managementRelevant: false,
    baseSalary: 4_600_000,
  },
  {
    code: "construction_manager",
    name: "施工管理",
    category: "建設・設備",
    description: "工事現場の工程・品質・安全管理",
    requiresTravel: true,
    requiresNightShift: false,
    requiresRelocation: true,
    minEducationLevel: null,
    managementRelevant: true,
    baseSalary: 6_000_000,
  },
  {
    code: "production_engineer",
    name: "生産技術",
    category: "製造",
    description: "製造ラインの設計・改善・立ち上げ",
    requiresTravel: false,
    requiresNightShift: false,
    requiresRelocation: false,
    minEducationLevel: "vocational" as const,
    managementRelevant: false,
    baseSalary: 5_600_000,
  },
  {
    code: "quality_control",
    name: "品質管理",
    category: "製造",
    description: "製品検査・品質保証・工程改善",
    requiresTravel: false,
    requiresNightShift: false,
    requiresRelocation: false,
    minEducationLevel: null,
    managementRelevant: false,
    baseSalary: 4_800_000,
  },
  {
    code: "sales",
    name: "営業",
    category: "営業",
    description: "法人・個人への提案営業",
    requiresTravel: true,
    requiresNightShift: false,
    requiresRelocation: false,
    minEducationLevel: null,
    managementRelevant: true,
    baseSalary: 5_000_000,
  },
] as const;

export const SKILLS = [
  { code: "fault_diagnosis", name: "故障診断", category: "技術" },
  { code: "machine_maintenance", name: "機械メンテナンス", category: "技術" },
  { code: "electrical_work", name: "電気配線・制御", category: "技術" },
  { code: "hydraulics", name: "油圧・空圧", category: "技術" },
  { code: "plc", name: "PLC・シーケンス制御", category: "技術" },
  { code: "cad", name: "CAD図面読解", category: "技術" },
  { code: "welding", name: "溶接・板金", category: "技術" },
  { code: "inspection", name: "検査・測定", category: "技術" },
  { code: "customer_support", name: "顧客対応", category: "対人" },
  { code: "proposal", name: "提案・折衝", category: "対人" },
  { code: "vendor_management", name: "協力会社の管理", category: "対人" },
  { code: "team_leading", name: "チームリーダー経験", category: "マネジメント" },
  { code: "process_improvement", name: "工程改善・カイゼン", category: "改善" },
  { code: "safety_management", name: "安全管理", category: "管理" },
  { code: "schedule_management", name: "工程・納期管理", category: "管理" },
  { code: "documentation", name: "報告書・手順書作成", category: "管理" },
  { code: "training", name: "後輩指導・教育", category: "マネジメント" },
  { code: "it_tools", name: "PC・業務システム操作", category: "IT" },
] as const;

export const CERTIFICATIONS = [
  { code: "auto_mechanic_2", name: "自動車整備士2級", category: "整備" },
  { code: "auto_mechanic_1", name: "自動車整備士1級", category: "整備" },
  { code: "electrician_2", name: "第二種電気工事士", category: "電気" },
  { code: "electrician_1", name: "第一種電気工事士", category: "電気" },
  { code: "electrical_chief_3", name: "第三種電気主任技術者", category: "電気" },
  { code: "boiler_2", name: "二級ボイラー技士", category: "設備" },
  { code: "refrigeration_3", name: "第三種冷凍機械責任者", category: "設備" },
  { code: "hazmat_b4", name: "危険物取扱者乙4", category: "設備" },
  { code: "forklift", name: "フォークリフト運転技能", category: "運搬" },
  { code: "kenchiku_shiko_2", name: "2級建築施工管理技士", category: "建設" },
  { code: "kanki_shiko_2", name: "2級管工事施工管理技士", category: "建設" },
  { code: "qc_2", name: "QC検定2級", category: "品質" },
  { code: "driver_license", name: "普通自動車免許", category: "共通" },
] as const;

/** occupation code -> [skill code, importance] */
export const OCCUPATION_SKILLS: Record<string, [string, number][]> = {
  auto_mechanic: [
    ["fault_diagnosis", 1.0],
    ["machine_maintenance", 0.9],
    ["customer_support", 0.6],
    ["hydraulics", 0.5],
    ["documentation", 0.4],
  ],
  facility_maintenance: [
    ["machine_maintenance", 1.0],
    ["fault_diagnosis", 0.9],
    ["plc", 0.7],
    ["electrical_work", 0.7],
    ["hydraulics", 0.6],
    ["safety_management", 0.5],
  ],
  field_service: [
    ["fault_diagnosis", 1.0],
    ["machine_maintenance", 0.9],
    ["customer_support", 0.9],
    ["documentation", 0.6],
    ["electrical_work", 0.5],
    ["it_tools", 0.4],
  ],
  industrial_service: [
    ["machine_maintenance", 1.0],
    ["fault_diagnosis", 0.9],
    ["plc", 0.8],
    ["customer_support", 0.7],
    ["hydraulics", 0.7],
    ["cad", 0.5],
  ],
  electrician: [
    ["electrical_work", 1.0],
    ["cad", 0.6],
    ["safety_management", 0.6],
    ["machine_maintenance", 0.5],
    ["documentation", 0.4],
  ],
  construction_manager: [
    ["schedule_management", 1.0],
    ["safety_management", 0.9],
    ["vendor_management", 0.9],
    ["cad", 0.7],
    ["documentation", 0.7],
    ["team_leading", 0.6],
  ],
  production_engineer: [
    ["process_improvement", 1.0],
    ["cad", 0.8],
    ["plc", 0.7],
    ["machine_maintenance", 0.6],
    ["documentation", 0.5],
  ],
  quality_control: [
    ["inspection", 1.0],
    ["process_improvement", 0.8],
    ["documentation", 0.7],
    ["it_tools", 0.5],
  ],
  sales: [
    ["proposal", 1.0],
    ["customer_support", 0.9],
    ["it_tools", 0.5],
    ["documentation", 0.5],
  ],
};

export const OCCUPATION_CERTIFICATIONS: Record<string, [string, number][]> = {
  auto_mechanic: [
    ["auto_mechanic_2", 1.0],
    ["auto_mechanic_1", 0.6],
    ["driver_license", 0.5],
  ],
  facility_maintenance: [
    ["electrician_2", 0.8],
    ["boiler_2", 0.7],
    ["refrigeration_3", 0.5],
    ["hazmat_b4", 0.5],
  ],
  field_service: [
    ["driver_license", 0.9],
    ["electrician_2", 0.6],
    ["auto_mechanic_2", 0.4],
  ],
  industrial_service: [
    ["driver_license", 0.8],
    ["electrician_2", 0.6],
    ["forklift", 0.4],
  ],
  electrician: [
    ["electrician_2", 1.0],
    ["electrician_1", 0.7],
    ["electrical_chief_3", 0.4],
  ],
  construction_manager: [
    ["kenchiku_shiko_2", 1.0],
    ["kanki_shiko_2", 0.7],
    ["driver_license", 0.5],
  ],
  production_engineer: [["qc_2", 0.6]],
  quality_control: [["qc_2", 1.0]],
  sales: [["driver_license", 0.7]],
};

export interface TransitionSeed {
  source: string;
  target: string;
  base: number;
  requiredSkills?: string[];
  preferredSkills?: string[];
  requiredCertifications?: string[];
  preferredCertifications?: string[];
  minimumExperienceYears?: number;
  notes?: string;
}

export const TRANSITIONS: TransitionSeed[] = [
  {
    source: "auto_mechanic",
    target: "field_service",
    base: 85,
    requiredSkills: ["fault_diagnosis"],
    preferredSkills: ["customer_support", "machine_maintenance"],
    preferredCertifications: ["driver_license"],
    minimumExperienceYears: 2,
    notes: "故障診断と顧客対応がそのまま活きる王道の転用先",
  },
  {
    source: "auto_mechanic",
    target: "facility_maintenance",
    base: 78,
    requiredSkills: ["machine_maintenance"],
    preferredSkills: ["hydraulics", "electrical_work"],
    minimumExperienceYears: 2,
    notes: "機械保全の基礎が共通。夜勤可否が分岐点",
  },
  {
    source: "auto_mechanic",
    target: "industrial_service",
    base: 70,
    requiredSkills: ["fault_diagnosis"],
    preferredSkills: ["hydraulics", "plc"],
    minimumExperienceYears: 3,
  },
  {
    source: "facility_maintenance",
    target: "field_service",
    base: 82,
    preferredSkills: ["customer_support", "fault_diagnosis"],
    minimumExperienceYears: 2,
  },
  {
    source: "facility_maintenance",
    target: "industrial_service",
    base: 84,
    preferredSkills: ["plc", "hydraulics"],
    minimumExperienceYears: 3,
  },
  {
    source: "facility_maintenance",
    target: "production_engineer",
    base: 66,
    preferredSkills: ["process_improvement", "cad"],
    minimumExperienceYears: 5,
  },
  {
    source: "electrician",
    target: "facility_maintenance",
    base: 84,
    requiredCertifications: ["electrician_2"],
    preferredSkills: ["machine_maintenance"],
    minimumExperienceYears: 2,
  },
  {
    source: "electrician",
    target: "construction_manager",
    base: 72,
    preferredSkills: ["schedule_management", "safety_management", "vendor_management"],
    preferredCertifications: ["kenchiku_shiko_2"],
    minimumExperienceYears: 5,
  },
  {
    source: "electrician",
    target: "field_service",
    base: 68,
    preferredSkills: ["customer_support", "fault_diagnosis"],
    minimumExperienceYears: 3,
  },
  {
    source: "quality_control",
    target: "production_engineer",
    base: 74,
    preferredSkills: ["process_improvement", "cad"],
    minimumExperienceYears: 3,
  },
  {
    source: "quality_control",
    target: "facility_maintenance",
    base: 60,
    preferredSkills: ["machine_maintenance"],
    minimumExperienceYears: 3,
  },
  {
    source: "production_engineer",
    target: "construction_manager",
    base: 58,
    preferredSkills: ["schedule_management", "vendor_management"],
    minimumExperienceYears: 5,
  },
  {
    source: "sales",
    target: "field_service",
    base: 52,
    preferredSkills: ["customer_support"],
    minimumExperienceYears: 3,
  },
  {
    source: "sales",
    target: "construction_manager",
    base: 55,
    preferredSkills: ["schedule_management", "vendor_management"],
    minimumExperienceYears: 5,
  },
  {
    source: "construction_manager",
    target: "industrial_service",
    base: 60,
    preferredSkills: ["vendor_management", "schedule_management"],
    minimumExperienceYears: 5,
  },
  {
    source: "field_service",
    target: "industrial_service",
    base: 88,
    preferredSkills: ["plc", "machine_maintenance"],
    minimumExperienceYears: 3,
  },
  {
    source: "field_service",
    target: "production_engineer",
    base: 62,
    preferredSkills: ["process_improvement", "cad"],
    minimumExperienceYears: 5,
  },
  {
    source: "industrial_service",
    target: "construction_manager",
    base: 60,
    preferredSkills: ["schedule_management", "safety_management"],
    minimumExperienceYears: 6,
  },
];

export const LOCATIONS = [
  {
    venueName: "西宮北口 ガーデンズ前",
    prefecture: "兵庫県",
    city: "西宮市",
    district: "高松町",
    venueType: "shopping_mall" as const,
    stationName: "西宮北口",
    regionCode: "hyogo_south",
    latitude: "34.738000",
    longitude: "135.361000",
  },
  {
    venueName: "千里中央 セルシー広場",
    prefecture: "大阪府",
    city: "豊中市",
    district: "新千里東町",
    venueType: "shopping_mall" as const,
    stationName: "千里中央",
    regionCode: "osaka_north",
    latitude: "34.807000",
    longitude: "135.496000",
  },
  {
    venueName: "梅田 grand front 前",
    prefecture: "大阪府",
    city: "大阪市北区",
    district: "大深町",
    venueType: "station" as const,
    stationName: "大阪",
    regionCode: "osaka_city",
    latitude: "34.704000",
    longitude: "135.495000",
  },
  {
    venueName: "高槻 アクトアモーレ前",
    prefecture: "大阪府",
    city: "高槻市",
    district: "白梅町",
    venueType: "shopping_street" as const,
    stationName: "高槻",
    regionCode: "osaka_north",
    latitude: "34.851000",
    longitude: "135.617000",
  },
  {
    venueName: "枚方 ビオルネ前",
    prefecture: "大阪府",
    city: "枚方市",
    district: "岡東町",
    venueType: "shopping_mall" as const,
    stationName: "枚方市",
    regionCode: "osaka_north",
    latitude: "34.814000",
    longitude: "135.650000",
  },
  {
    venueName: "尼崎 コーナン前",
    prefecture: "兵庫県",
    city: "尼崎市",
    district: "潮江",
    venueType: "home_center" as const,
    stationName: "尼崎",
    regionCode: "hyogo_south",
    latitude: "34.733000",
    longitude: "135.410000",
  },
];

export const AGENT_COMPANIES = [
  {
    name: "テクノキャリア・パートナーズ",
    contactEmail: "agent@techno-career.example.com",
    userName: "田村 直樹",
    userEmail: "agent1@example.com",
    specialties: [
      ["field_service", 5],
      ["industrial_service", 5],
      ["facility_maintenance", 4],
      ["auto_mechanic", 3],
    ] as [string, number][],
    regionCodes: ["osaka_city", "osaka_north", "hyogo_south"],
    minSalary: 3_500_000,
    maxSalary: 9_000_000,
    fees: [
      { eventType: "agent_interview_completed" as const, amount: 30_000 },
      { eventType: "offer" as const, amount: 120_000 },
      { eventType: "joined" as const, amount: 400_000 },
    ],
    notes: "製造・サービスエンジニア領域に強い",
  },
  {
    name: "関西モノづくり転職センター",
    contactEmail: "agent@kansai-mono.example.com",
    userName: "杉本 千夏",
    userEmail: "agent2@example.com",
    specialties: [
      ["facility_maintenance", 5],
      ["production_engineer", 5],
      ["quality_control", 4],
      ["electrician", 3],
    ] as [string, number][],
    regionCodes: ["osaka_north", "kyoto_city", "hyogo_south", "nara"],
    minSalary: 3_000_000,
    maxSalary: 7_500_000,
    fees: [
      { eventType: "agent_interview_completed" as const, amount: 25_000 },
      { eventType: "offer" as const, amount: 100_000 },
      { eventType: "joined" as const, amount: 350_000 },
    ],
    notes: "関西の中堅メーカーに広いネットワーク",
  },
  {
    name: "ビルドキャリア",
    contactEmail: "agent@buildcareer.example.com",
    userName: "森 亮介",
    userEmail: "agent3@example.com",
    specialties: [
      ["construction_manager", 5],
      ["electrician", 5],
      ["industrial_service", 3],
    ] as [string, number][],
    regionCodes: ["osaka_city", "osaka_north", "kyoto_city"],
    minSalary: 4_000_000,
    maxSalary: 12_000_000,
    fees: [
      { eventType: "agent_accepted" as const, amount: 10_000 },
      { eventType: "agent_interview_completed" as const, amount: 40_000 },
      { eventType: "offer" as const, amount: 150_000 },
      { eventType: "joined" as const, amount: 500_000 },
    ],
    notes: "建設・電気設備の求人が中心",
  },
];

export const SALES_USERS = [
  { name: "山下 蓮", email: "sales1@example.com", skill: 1.15 },
  { name: "岡田 美咲", email: "sales2@example.com", skill: 1.0 },
  { name: "近藤 大輔", email: "sales3@example.com", skill: 0.82 },
  { name: "白石 詩織", email: "sales4@example.com", skill: 0.95 },
];

export const INCENTIVE_RULES = [
  {
    name: "診断完了",
    eventType: "diagnosis_completed" as const,
    amountYen: 200,
    priority: 100,
    conditions: null,
  },
  {
    name: "リード登録",
    eventType: "lead_registered" as const,
    amountYen: 800,
    priority: 100,
    conditions: null,
  },
  {
    name: "面談予約",
    eventType: "interview_booked" as const,
    amountYen: 1_500,
    priority: 100,
    conditions: null,
  },
  {
    name: "面談着座",
    eventType: "interview_completed" as const,
    amountYen: 4_000,
    priority: 100,
    conditions: null,
  },
  {
    name: "有効候補者（ランクB以上）",
    eventType: "candidate_qualified" as const,
    amountYen: 3_000,
    priority: 100,
    conditions: { minMatchRank: "B" as const },
  },
  {
    name: "エージェント送客",
    eventType: "agent_referred" as const,
    amountYen: 5_000,
    priority: 100,
    conditions: null,
  },
  {
    name: "内定",
    eventType: "offer" as const,
    amountYen: 10_000,
    priority: 100,
    conditions: null,
  },
  {
    name: "入社決定",
    eventType: "joined" as const,
    amountYen: 30_000,
    priority: 100,
    conditions: null,
  },
];
